name: Publish Packages

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.*
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish Countries.Net
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: src/Countries/Countries.csproj
          VERSION_FILE_PATH: src/Directory.Build.props
          NUGET_KEY: ${{secrets.NUGET_KEY}}
          NUGET_SOURCE: https://api.nuget.org
          INCLUDE_SYMBOLS: true
      - name: Publish Countries.DependencyInjection
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: src/Countries.DependencyInjection/Countries.DependencyInjection.csproj
          VERSION_FILE_PATH: src/Directory.Build.props
          NUGET_KEY: ${{secrets.NUGET_KEY}}
          NUGET_SOURCE: https://api.nuget.org
          INCLUDE_SYMBOLS: true
